site_name: Ilja's Initiative for Input Validation
repo_url: https://github.com/systopia/be.aivl.i3val
theme: material

pages:
- 'Home': index.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
